### ISSUE TITLE
Failing test: requestToken__ensure_the_message_published_with_a_wildcard_____does_not_have_a_clientId

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1037]
When run locally with `make test_macOS` and `make test_iOS`:

```
✗ requestToken__ensure_the_message_published_with_a_wildcard_____does_not_have_a_clientId, expected to have Array<ARTMessage> with count 1, got 0
✗ requestToken__ensure_the_message_published_with_a_wildcard_____does_not_have_a_clientId, unexpected exception raised: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
```

Also failing [in Travis](https://travis-ci.org/github/ably/ably-cocoa/jobs/703983171#L2344).

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-342) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
