### ISSUE TITLE
Failing test: Channel__history__should_return_a_PaginatedResult_page

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1039]
When run locally with `make test_macOS` and `make test_iOS`:

```
✗ Channel__history__should_return_a_PaginatedResult_page, expected to have Array<ARTMessage> with count 1, got 0
✗ Channel__history__should_return_a_PaginatedResult_page, unexpected exception raised: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
```

and

```
[19:05:43]: ▸     ✗ Channel__history__should_return_a_PaginatedResult_page, expected to have Array<ARTMessage> with count 1, got 0
[19:05:43]: ▸     ✗ Channel__history__should_return_a_PaginatedResult_page, unexpected exception raised: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-344) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
