### ISSUE TITLE
Failing test: Presence__private_and_internal_PresenceMap_containing_only_members_that_match_the_current_connectionId__events_applied_to_presence_map__should_be_applied_to_ENTER__PRESENT_or_UPDATE_events_with_a_connectionId_that_matches_the_current_client_

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1042]
When run locally with `make test_macOS`:

```
✗ Presence__private_and_internal_PresenceMap_containing_only_members_that_match_the_current_connectionId__events_applied_to_presence_map__should_be_applied_to_ENTER__PRESENT_or_UPDATE_events_with_a_connectionId_that_matches_the_current_client_s_connectionId, Waited more than 10.0 seconds
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-347) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
