### ISSUE TITLE
Failing test: history__query_arguments__limit_items_result

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1048]
When run locally with `make test_macOS`:

```
    ✗ history__query_arguments__limit_items_result, expected to be true, got <false>
    ✗ history__query_arguments__limit_items_result, expected to be false, got <true>
    ✗ history__query_arguments__limit_items_result, PaginatedResult has no items
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-353) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
