### ISSUE TITLE
Fix presence implementation according to reference one (ably-go)

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1890]
Looks like a lot of outdated code in the presence, needs to be updated in according to reference implementation/specs.

Related issue - https://github.com/ably/ably-cocoa/issues/1889

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4698) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
TODOs
1. Refactor `onMessage` implementation with relevant `newerThan` checks => https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/realtime_presence.go#L291
2. Remove use of [_syncSessionId](https://github.com/ably/ably-cocoa/blob/ecec03dc2a949ca2f5e670b714aaaa0418f5b6bf/Source/ARTRealtimePresence.m#L178). Currently, it's being used for marking members as updated. It causes field to be initialized in [ARTPresenceMessage.m](https://github.com/ably/ably-cocoa/blob/ecec03dc2a949ca2f5e670b714aaaa0418f5b6bf/Source/ARTPresenceMessage.m#L13) ( doesn't go as per spec ). We don't have syncSessionId in any other SDK's, seems this is there since very old spec. I would recommend to use [beforeSyncMembers](https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/realtime_presence.go#L206) as a list instead.
3. Please also self-review ably-cocoa presence code with respect to ably-go implementation => https://github.com/ably/ably-go/blob/main/ably/realtime_presence.go

**Comment by maratal** [comment]
1. I think that checking `nil` [in](https://github.com/ably/ably-cocoa/blob/ecec03dc2a949ca2f5e670b714aaaa0418f5b6bf/Source/ARTPresenceMessage.m#L77) `isNewerThan` is okay and lets to avoid this check earlier. I've introduced additional check on whether the member exists prior to removing it. Also I think that the code duplication [here](https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/realtime_presence.go#L291) can be also avoided, so I left cocoa implementation intact here, except renaming methods to something that I think makes more sense to reduce confusion.
2. I think that introducing additional array to track what was updated is unnecessary complication. Instead simple flag `wasUpdated` within a message can be used. I tried that (didn't rename the var though) and it works.
3. WIP

WDYT @sacOO7
