### ISSUE TITLE
Flaky test: RTN10b (connection serial increase) - Connection__serial__should_not_update_when_a_message_is_sent_but_increments_by_one_when_ACK_is_received

### ISSUE THREAD

**Issue by tcard** [ably/ably-cocoa#932]
We're seeing this a lot in Travis:

```
[09:38:12]: ▸     ✗ Connection__serial__should_not_update_when_a_message_is_sent_but_increments_by_one_when_ACK_is_received, expected to equal <1>, got <2>
```

I can't reproduce this on my machine, so the flakiness probably has to do with Travis limited system resources.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-386) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
