### ISSUE TITLE
Flaky test: JSON encoder: ignore invalid response - Utilities__JSON_Encoder__in_Rest__should_ignore_invalid_response_payload

### ISSUE THREAD

**Issue by tcard** [ably/ably-cocoa#936]
```
✗ Utilities__JSON_Encoder__in_Rest__should_ignore_invalid_response_payload, Error is nil
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-388) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
