### ISSUE TITLE
Flaky test: RSH1b2 (push admin should list devices by id) - Device_Registrations__list__should_list_devices_by_client_id

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-cocoa#956]
Sometimes we get this on Travis:

```
3426    ✗ Device_Registrations__list__should_list_devices_by_client_id
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-391) by [Unito](https://www.unito.io)

**Comment by ricardopereira** [comment]
An intermittent crash can happen in the PushAdmin tests. For example (PushAdmin.swift:444), for some reason if the `realtime.push.admin.deviceRegistrations.list` call takes more than the `waitUntil` timeout, then an uncaught NSInternalInconsistencyException can happen with the reason: 'Attempted to report a test failure to XCTest while no test case was running'. Since the `realtime.push.admin.deviceRegistrations.list` request isn't cancelled when the test case ends, the callback will be called, for example with a network timeout error, and the crash will occur when the `fail` method is performed because the test case doesn't exist anymore.

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
