### ISSUE TITLE
Flaky test: RSH3a2c (should send event GotPushDeviceDetails) - Activation_state_machine__State_NotActivated__on_Event_CalledActivate__if_the_local_device_has_the_necessary_push_details_should_send_event_GotPushDeviceDetails

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-cocoa#958]
Sometimes we get this on Travis:

```
[10:13:18]: ▸     ✗ Activation_state_machine__State_NotActivated__on_Event_CalledActivate__if_the_local_device_has_the_necessary_push_details_should_send_event_GotPushDeviceDetails, Test crashed
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-392) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Closing outdated issue. The codebase changed drastically since then and all skipped tests were unskipped, see PRs for https://github.com/ably/ably-cocoa/issues/1406 and https://github.com/ably/ably-cocoa/issues/1848

If you encounter frequently failing test again, please create a new issue with a best guess why it might be happening.
